// Anlat Bakalım kartları: "Kelime: yasak1, yasak2, yasak3, yasak4".
// Aileye uygun, Türkçe. Oyun başında karıştırılır; bir oyunda tekrar etmez.

export type TabooCard = { word: string; taboo: string[]; category: string };

const DECK: Record<string, string[]> = {
  "Yemek ve içecek": [
    "Lahmacun: kıyma, hamur, fırın, ince",
    "Baklava: şerbet, fıstık, tatlı, yufka",
    "Menemen: yumurta, domates, biber, kahvaltı",
    "Ayran: yoğurt, su, tuz, içecek",
    "Simit: susam, halka, çay, fırın",
    "Pizza: İtalya, peynir, hamur, dilim",
    "Hamburger: köfte, ekmek, patates, fast food",
    "Dondurma: soğuk, külah, yaz, tatlı",
    "Türk kahvesi: fincan, köpük, fal, telve",
    "Çay: demlik, bardak, şeker, Rize",
    "Mantı: yoğurt, hamur, Kayseri, kıyma",
    "Kumpir: patates, Ortaköy, peynir, malzeme",
    "Döner: et, tavuk, dürüm, şiş",
    "Sushi: Japon, pirinç, balık, çubuk",
    "Pide: Karadeniz, hamur, kaşar, fırın",
    "Kokoreç: bağırsak, ekmek, kuzu, ızgara",
    "Künefe: kadayıf, peynir, Hatay, şerbet",
    "Sütlaç: pirinç, süt, tatlı, fırın",
    "Mercimek çorbası: kırmızı, limon, kase, sıcak",
    "Karpuz: yaz, kırmızı, çekirdek, peynir",
    "Limonata: limon, şeker, buz, ekşi",
    "Omlet: yumurta, tava, kahvaltı, peynir",
    "Patlıcan: mor, karnıyarık, sebze, közlenmiş",
    "Börek: yufka, peynir, ıspanak, fırın",
    "İskender: döner, tereyağı, yoğurt, Bursa",
    "Köfte: kıyma, ızgara, İnegöl, yuvarlak",
    "Waffle: çikolata, meyve, hamur, kare",
    "Kruvasan: Fransız, tereyağı, hilal, kahvaltı",
    "Smoothie: meyve, blender, içecek, muz",
    "Sahlep: kış, tarçın, sıcak, süt",
    "Boza: ekşi, kış, leblebi, tarçın",
    "Popcorn: mısır, sinema, patlamak, tuz",
    "Çikolata: kakao, tatlı, bitter, sütlü",
    "Bal: arı, petek, sarı, tatlı",
    "Zeytin: yeşil, siyah, kahvaltı, yağ",
    "Pilav: pirinç, tereyağı, tabak, bulgur",
    "Salata: marul, domates, sos, yeşillik",
    "Tost: kaşar, ekmek, makine, sucuk",
    "Gözleme: hamur, sac, peynir, patates",
    "Çiğ köfte: bulgur, acı, dürüm, marul",
    "Hünkar beğendi: patlıcan, et, beğendi, Osmanlı",
    "Turşu: sirke, kavanoz, salatalık, suyu",
    "Kek: fırın, un, dilim, yumurta",
    "Pasta: doğum günü, mum, krema, dilim",
    "Makarna: İtalya, haşlamak, sos, spagetti",
    "Kahve: kafein, fincan, sabah, espresso",
    "Portakal suyu: sıkmak, vitamin, kahvaltı, turuncu",
    "Maden suyu: gaz, şişe, Kızılay, mide",
    "Muz: sarı, kabuk, maymun, meyve",
    "Çilek: kırmızı, meyve, bahar, reçel",
    "Reçel: kavanoz, meyve, kahvaltı, tatlı",
    "Peynir: beyaz, kaşar, süt, kahvaltı",
    "Sucuk: yumurta, baharat, kangal, kahvaltı",
    "Lokum: Türk, şeker, gül, pudra",
    "Aşure: Muharrem, tatlı, buğday, komşu",
    "Kestane: kış, sokak, kebap, kabuk",
    "Mısır: koçan, sokak, sarı, haşlama",
    "Tavuk şiş: ızgara, şiş, tavuk, mangal",
    "Mangal: kömür, piknik, et, ateş",
    "Kebap: Adana, Urfa, et, şiş",
  ],
  "Gündelik hayat": [
    "Şemsiye: yağmur, açmak, ıslak, sap",
    "Asansör: kat, yukarı, düğme, bina",
    "Buzdolabı: soğuk, mutfak, kapı, yiyecek",
    "Çamaşır makinesi: yıkamak, deterjan, kıyafet, sıkma",
    "Telefon: aramak, mesaj, şarj, ekran",
    "Şarj aleti: kablo, pil, priz, telefon",
    "Kumanda: televizyon, kanal, düğme, uzaktan",
    "Yastık: uyku, yatak, baş, kılıf",
    "Diş fırçası: macun, diş, sabah, fırçalamak",
    "Ayna: yansıma, cam, bakmak, banyo",
    "Saat: zaman, akrep, yelkovan, kol",
    "Alarm: sabah, uyanmak, ses, saat",
    "Cüzdan: para, kart, cep, deri",
    "Anahtar: kapı, kilit, açmak, cep",
    "Gözlük: göz, cam, görmek, numara",
    "Şapka: baş, güneş, kafa, kep",
    "Eldiven: el, kış, parmak, soğuk",
    "Atkı: boyun, kış, yün, sıcak",
    "Terlik: ayak, ev, giymek, banyo",
    "Valiz: tatil, bavul, tekerlek, havalimanı",
    "Bisiklet: pedal, tekerlek, sürmek, zincir",
    "Otobüs: durak, şoför, bilet, yolcu",
    "Metro: yer altı, istasyon, ray, kart",
    "Taksi: sarı, şoför, taksimetre, araba",
    "Trafik: araba, kırmızı, sıkışık, yol",
    "Tatil: deniz, otel, izin, yaz",
    "Doğum günü: pasta, mum, hediye, yaş",
    "Düğün: gelin, damat, nikah, halay",
    "Bayram: şeker, el öpmek, harçlık, ziyaret",
    "Pazar: sebze, meyve, tezgah, alışveriş",
    "Market: alışveriş, kasa, sepet, raf",
    "Kasa: para, ödemek, fiş, sıra",
    "Fatura: elektrik, su, ödemek, ay",
    "Selfie: fotoğraf, kendi, telefon, poz",
    "Instagram: fotoğraf, takipçi, hikaye, beğeni",
    "Şifre: gizli, giriş, harf, unutmak",
    "Mesaj: yazmak, telefon, WhatsApp, göndermek",
    "Uyku: yatak, gece, rüya, gözler",
    "Rüya: uyku, gece, görmek, kabus",
    "Horlamak: uyku, ses, burun, gece",
    "Hapşırmak: burun, çok yaşa, grip, mendil",
    "Kahvaltı: sabah, çay, yumurta, peynir",
    "Piknik: çimen, örtü, mangal, park",
    "Kamp: çadır, ateş, doğa, uyku tulumu",
    "Hediye: paket, kurdele, doğum günü, almak",
    "Mum: ateş, ışık, pasta, eriyen",
    "Balon: şişirmek, patlamak, renkli, uçmak",
    "Kar topu: kar, kış, atmak, yuvarlak",
    "Kardan adam: havuç, kış, kar, şapka",
    "Havai fişek: patlama, gökyüzü, yılbaşı, renk",
    "Yılbaşı: aralık, çam ağacı, hediye, saat",
    "Ödev: okul, öğretmen, ders, yapmak",
    "Karne: okul, not, tatil, takdir",
    "Teneffüs: okul, zil, ara, bahçe",
    "Sınav: soru, kalem, puan, test",
    "Kütüphane: kitap, sessiz, okumak, raf",
    "Battaniye: örtü, sıcak, kanepe, kış",
    "Kanepe: oturmak, salon, koltuk, uzanmak",
    "Perde: pencere, kumaş, kapatmak, güneş",
    "Halı: yer, kilim, desen, yıkamak",
  ],
  "Meslekler": [
    "Doktor: hastane, hasta, ilaç, muayene",
    "Öğretmen: okul, ders, öğrenci, sınıf",
    "Aşçı: mutfak, yemek, şef, tencere",
    "Garson: sipariş, masa, servis, tepsi",
    "Berber: saç, sakal, makas, tıraş",
    "Pilot: uçak, havalimanı, kaptan, uçmak",
    "İtfaiyeci: yangın, su, hortum, kırmızı",
    "Polis: suç, düdük, karakol, hırsız",
    "Avukat: mahkeme, dava, hakim, savunma",
    "Hakim: mahkeme, karar, tokmak, dava",
    "Diş hekimi: diş, çürük, dolgu, ağız",
    "Eczacı: ilaç, reçete, nöbet, eczane",
    "Fırıncı: ekmek, fırın, hamur, sabah",
    "Kasap: et, bıçak, kıyma, dükkan",
    "Postacı: mektup, kargo, zarf, kapı",
    "Ressam: tablo, boya, fırça, tuval",
    "Fotoğrafçı: kamera, çekmek, poz, flaş",
    "Mimar: bina, çizim, proje, tasarım",
    "Astronot: uzay, roket, ay, NASA",
    "Futbolcu: top, gol, takım, saha",
    "Hemşire: hastane, iğne, doktor, hasta",
    "Veteriner: hayvan, kedi, köpek, aşı",
    "Çiftçi: tarla, traktör, hasat, köy",
    "Balıkçı: olta, ağ, tekne, deniz",
    "Terzi: dikiş, makas, kumaş, ölçü",
    "Şoför: araba, direksiyon, yol, ehliyet",
    "Kaptan: gemi, deniz, dümen, tayfa",
    "Sihirbaz: şapka, tavşan, hile, gösteri",
    "Palyaço: kırmızı burun, sirk, güldürmek, makyaj",
    "Gazeteci: haber, röportaj, muhabir, mikrofon",
    "Barista: kahve, espresso, köpük, kafe",
    "Kuaför: saç, boya, fön, makas",
    "Yazılımcı: bilgisayar, kod, program, uygulama",
    "Bekçi: gece, düdük, sokak, nöbet",
    "Tamirci: alet, bozuk, araba, tamir",
  ],
  "Yerler": [
    "Galata Kulesi: İstanbul, Beyoğlu, kule, manzara",
    "Kapadokya: balon, peri bacası, Nevşehir, kaya",
    "Pamukkale: traverten, beyaz, Denizli, havuz",
    "Efes: antik, Selçuk, kütüphane, İzmir",
    "Boğaz: İstanbul, köprü, vapur, deniz",
    "Kız Kulesi: Üsküdar, deniz, kule, efsane",
    "Ayasofya: cami, müze, İstanbul, kubbe",
    "Kapalıçarşı: dükkan, alışveriş, kapalı, İstanbul",
    "Anıtkabir: Ankara, Atatürk, ziyaret, mozole",
    "Uludağ: kayak, Bursa, kar, dağ",
    "Paris: Fransa, Eyfel, aşk, Louvre",
    "Venedik: gondol, kanal, İtalya, su",
    "Mısır piramitleri: firavun, çöl, Kahire, üçgen",
    "Çin Seddi: duvar, uzun, Çin, uzay",
    "Havalimanı: uçak, bilet, pasaport, kalkış",
    "Hastane: doktor, hasta, ameliyat, acil",
    "Sinema: film, perde, patlamış mısır, bilet",
    "Tiyatro: sahne, oyuncu, perde, oyun",
    "Müze: tarih, eser, sergi, eski",
    "Hayvanat bahçesi: hayvan, kafes, aslan, ziyaret",
    "Lunapark: dönme dolap, oyuncak, eğlence, bilet",
    "Plaj: kum, deniz, şezlong, güneş",
    "Havuz: yüzmek, su, mayo, otel",
    "Akvaryum: balık, cam, su, deniz canlısı",
    "Stadyum: maç, futbol, tribün, taraftar",
    "Kafe: kahve, oturmak, masa, sohbet",
    "Restoran: yemek, garson, menü, masa",
    "Otel: oda, resepsiyon, tatil, yatak",
    "Okul: öğrenci, öğretmen, sınıf, ders",
    "Köy: tarla, çiftlik, hayvan, şehir",
    "Ada: deniz, vapur, Büyükada, su",
    "Çöl: kum, sıcak, deve, vaha",
    "Orman: ağaç, yeşil, hayvan, doğa",
    "Şelale: su, akmak, yüksek, doğa",
    "Mağara: karanlık, kaya, yarasa, dağ",
    "Kale: sur, tarih, savunma, eski",
    "Saray: kral, sultan, Topkapı, Dolmabahçe",
    "Cami: minare, namaz, ezan, kubbe",
    "Kuyumcu: altın, yüzük, takı, vitrin",
    "Eczane: ilaç, reçete, nöbetçi, eczacı",
  ],
  "Spor ve oyun": [
    "Futbol: top, gol, kale, maç",
    "Basketbol: pota, top, smaç, üçlük",
    "Voleybol: file, smaç, servis, pasör",
    "Tenis: raket, kort, top, file",
    "Yüzme: havuz, su, mayo, kulaç",
    "Satranç: şah, vezir, piyon, tahta",
    "Tavla: zar, pul, mars, kahvehane",
    "Okey: taş, ıstaka, dört, el",
    "Bowling: lobut, top, strike, salon",
    "Bilardo: ıstaka, top, masa, delik",
    "Kayak: kar, dağ, kayak merkezi, kış",
    "Sörf: dalga, tahta, deniz, rüzgar",
    "Bisiklet yarışı: pedal, Tur, yarış, kask",
    "Maraton: koşu, kilometre, uzun, yarış",
    "Penaltı: gol, kaleci, futbol, nokta",
    "Ofsayt: hakem, futbol, bayrak, kural",
    "Hakem: düdük, kart, maç, karar",
    "Kırmızı kart: hakem, ihraç, futbol, oyun dışı",
    "Olimpiyat: madalya, halka, dünya, oyun",
    "Altın madalya: birinci, olimpiyat, kazanmak, sarı",
    "Boks: eldiven, ring, yumruk, raunt",
    "Güreş: Kırkpınar, yağlı, minder, pehlivan",
    "Yoga: esneme, nefes, mat, meditasyon",
    "Saklambaç: saymak, saklanmak, ebe, bulmak",
    "Körebe: göz, bağlamak, yakalamak, oyun",
    "Uçurtma: ip, rüzgar, gökyüzü, uçurmak",
    "Yapboz: parça, birleştirmek, resim, puzzle",
    "Taş kağıt makas: el, oyun, kazanmak, üç",
    "Dart: ok, hedef, tahta, atmak",
    "Taraftar: tribün, takım, tezahürat, forma",
  ],
  "Film, dizi ve müzik": [
    "Çizgi film: animasyon, çocuk, karakter, televizyon",
    "Süper kahraman: pelerin, güç, kurtarmak, kötü",
    "Korku filmi: korkmak, hayalet, gece, çığlık",
    "Romantik komedi: aşk, gülmek, film, çift",
    "Dizi: bölüm, sezon, televizyon, final",
    "Fragman: film, tanıtım, kısa, vizyon",
    "Altyazı: film, yazı, çeviri, ekran",
    "Oscar: ödül, heykelcik, Hollywood, aktör",
    "Kırmızı halı: ünlü, ödül, gece, fotoğraf",
    "Konser: sahne, şarkıcı, bilet, kalabalık",
    "Gitar: tel, çalmak, akor, müzik",
    "Davul: zurna, vurmak, ritim, düğün",
    "Piyano: tuş, siyah, beyaz, çalmak",
    "Bağlama: saz, tel, türkü, telli",
    "Mikrofon: ses, şarkı, konuşmak, sahne",
    "Karaoke: şarkı, söylemek, ekran, mikrofon",
    "Kulaklık: müzik, kulak, dinlemek, kablosuz",
    "Radyo: frekans, dinlemek, şarkı, spiker",
    "Yönetmen: film, set, kamera, motor",
    "Kamera: çekmek, film, lens, kayıt",
    "Sinema bileti: koltuk, salon, film, gişe",
    "Hayalet: ruh, korku, beyaz, görünmez",
    "Vampir: kan, diş, gece, Drakula",
    "Robot: makine, metal, yapay zeka, insan",
    "Uzaylı: UFO, uzay, yeşil, gezegen",
    "Prenses: kraliçe, saray, taç, masal",
    "Ejderha: ateş, kanat, masal, kertenkele",
    "Korsan: gemi, hazine, deniz, göz bandı",
    "Dedektif: ipucu, gizem, katil, büyüteç",
    "Masal: bir varmış, çocuk, uyku, peri",
    "Halay: düğün, el ele, oynamak, davul",
    "Dans: müzik, ritim, oynamak, adım",
    "Şarkı: söylemek, nakarat, melodi, müzik",
    "Alkış: el, çırpmak, tebrik, sahne",
    "Sihirli değnek: büyü, sihirbaz, peri, sallamak",
  ],
  "Hayvanlar ve doğa": [
    "Kedi: miyav, tüy, fare, evcil",
    "Köpek: hav, kemik, sadık, kuyruk",
    "Aslan: kral, yele, orman, kükremek",
    "Fil: hortum, büyük, gri, kulak",
    "Zürafa: boyun, uzun, benek, Afrika",
    "Penguen: buz, siyah beyaz, kutup, yürümek",
    "Maymun: muz, ağaç, tırmanmak, şempanze",
    "Kaplumbağa: kabuk, yavaş, sürüngen, deniz",
    "Tavşan: havuç, kulak, zıplamak, beyaz",
    "Arı: bal, iğne, vızıltı, kovan",
    "Kelebek: kanat, renkli, tırtıl, çiçek",
    "Yunus: deniz, zeki, atlamak, memeli",
    "Köpek balığı: deniz, diş, yüzgeç, tehlikeli",
    "Ahtapot: kol, sekiz, deniz, mürekkep",
    "Baykuş: gece, göz, kuş, hu hu",
    "Papağan: konuşmak, kuş, renkli, tüy",
    "Horoz: sabah, ötmek, tavuk, ibik",
    "İnek: süt, çiftlik, möö, otlamak",
    "Koyun: yün, kuzu, sürü, meee",
    "Deve: hörgüç, çöl, su, kervan",
    "Kurbağa: vırak, yeşil, zıplamak, göl",
    "Yılan: sürünmek, zehir, tıslamak, uzun",
    "Kartal: kuş, uçmak, pençe, yüksek",
    "Ayı: bal, kış uykusu, orman, kahverengi",
    "Kanguru: kese, Avustralya, zıplamak, yavru",
    "Gökkuşağı: renk, yağmur, güneş, yedi",
    "Yanardağ: lav, patlamak, dağ, ateş",
    "Deprem: sarsıntı, fay, yer, büyüklük",
    "Şimşek: gök gürültüsü, ışık, fırtına, yıldırım",
    "Kar: beyaz, kış, yağmak, soğuk",
    "Güneş: sıcak, sarı, gündüz, ışık",
    "Ay: gece, dolunay, gökyüzü, hilal",
    "Yıldız: gece, parlamak, gökyüzü, kayan",
    "Deniz: dalga, mavi, tuzlu, kıyı",
    "Kum: plaj, çöl, kale, sarı",
    "Çiçek: koku, gül, bahçe, yaprak",
    "Ağaç: dal, yaprak, kök, orman",
    "Kaktüs: diken, çöl, saksı, su",
    "Bulut: gökyüzü, beyaz, yağmur, pamuk",
    "Rüzgar: esmek, hava, fırtına, uçurtma",
  ],
};

export const TABOO_CARDS: TabooCard[] = Object.entries(DECK).flatMap(([category, rows]) =>
  rows.map((row) => {
    const [word, rest] = row.split(":");
    return {
      word: word.trim(),
      taboo: rest
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean)
        .slice(0, 4),
      category,
    };
  })
);

export const TABOO_CATEGORIES = Object.keys(DECK);

export function shuffle<T>(items: T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
