-- OZT DIGITAL MENU
-- 1) Hata kayıtları (sistem paneli → Hatalar)
-- 2) Sözleşme onayları (işletme paneli ilk girişte)
--
-- İki tablo da yalnızca sunucudan (service role) okunur ve yazılır;
-- tarayıcıdan erişim yoktur (RLS açık, politika yok).

-- ---------------------------------------------------------------
-- 1) Hata kayıtları
--    Aynı hata (kaynak + mesaj + sayfa) tek satırda toplanır, sayısı artar.
--    Kişisel veri tutulmaz: sorgu metni (masa kodu vb.) atılır, e-posta ve
--    uzun sayılar sunucuda maskelenir. 90 günden eski kayıtlar silinir.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.error_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fingerprint text NOT NULL UNIQUE,
  source text NOT NULL CHECK (source IN ('server', 'client')),
  message text NOT NULL,
  stack text,
  path text,
  route text,
  digest text,
  user_agent text,
  occurrences integer NOT NULL DEFAULT 1,
  first_seen timestamptz NOT NULL DEFAULT now(),
  last_seen timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz
);

CREATE INDEX IF NOT EXISTS error_logs_last_seen_idx ON public.error_logs (last_seen DESC);

ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.error_logs FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.log_error(
  p_fingerprint text,
  p_source text,
  p_message text,
  p_stack text,
  p_path text,
  p_route text,
  p_digest text,
  p_user_agent text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.error_logs AS e
    (fingerprint, source, message, stack, path, route, digest, user_agent)
  VALUES (
    left(p_fingerprint, 64),
    p_source,
    left(p_message, 1000),
    left(p_stack, 4000),
    left(p_path, 300),
    left(p_route, 300),
    left(p_digest, 100),
    left(p_user_agent, 300)
  )
  ON CONFLICT (fingerprint) DO UPDATE
  SET occurrences = e.occurrences + 1,
      last_seen = now(),
      -- Çözüldü denmiş hata tekrar ederse yeniden açılır.
      resolved_at = NULL,
      stack = COALESCE(EXCLUDED.stack, e.stack),
      digest = COALESCE(EXCLUDED.digest, e.digest),
      user_agent = COALESCE(EXCLUDED.user_agent, e.user_agent);

  DELETE FROM public.error_logs WHERE last_seen < now() - interval '90 days';
END;
$$;

REVOKE ALL ON FUNCTION public.log_error(text, text, text, text, text, text, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.log_error(text, text, text, text, text, text, text, text) TO service_role;

-- ---------------------------------------------------------------
-- 2) Sözleşme onayları
--    Kullanım şartları, mesafeli satış / iptal-iade, veri işleme
--    sözleşmesi ve aydınlatma metni; hangi sürüm, kim, ne zaman.
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.legal_acceptances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id bigint NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  user_email text,
  version text NOT NULL,
  documents text[] NOT NULL,
  ip_address text,
  user_agent text,
  accepted_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS legal_acceptances_restaurant_idx
  ON public.legal_acceptances (restaurant_id, version);

ALTER TABLE public.legal_acceptances ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.legal_acceptances FROM anon, authenticated;
