-- OZT DIGITAL MENU
-- Telefona bildirim (web push): yeni sipariş, sipariş hazır, garson çağrısı.
--
-- Akış: sipariş / çağrı kaydı oluşunca tetikleyici, sitenin
-- /api/bildirim/gonder adresine (pg_net ile, işlem tamamlandıktan sonra)
-- yalnızca kayıt numarasını gönderir. Site, gizli anahtarı doğrular, kaydı
-- kendisi okur ve bildirimi o restoranın abone cihazlarına yollar.
--
-- Sipariş ve çağrılar bu yüzden asla başarısız olmaz: bildirim
-- gönderilemezse hata yutulur. Bildirim açmamış restoran için hiç istek
-- gönderilmez.

CREATE EXTENSION IF NOT EXISTS pg_net;

-- ---------------------------------------------------------------
-- 1) Abone cihazlar
-- ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id bigint NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('yonetici', 'garson', 'mutfak')),
  endpoint text NOT NULL UNIQUE CHECK (char_length(endpoint) <= 1000),
  p256dh text NOT NULL CHECK (char_length(p256dh) <= 200),
  auth text NOT NULL CHECK (char_length(auth) <= 100),
  user_agent text CHECK (user_agent IS NULL OR char_length(user_agent) <= 300),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS push_subscriptions_restaurant_idx ON public.push_subscriptions (restaurant_id, role);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_idx ON public.push_subscriptions (user_id);

-- Yalnızca sunucu (service role) okur ve yazar.
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.push_subscriptions FROM anon, authenticated;

-- ---------------------------------------------------------------
-- 2) Gönderim ayarı (tek satır)
-- ---------------------------------------------------------------

-- webhook_secret otomatik üretilir; site bu tablodan okuyup doğrular.
-- Alan adı değişirse webhook_url güncellenmelidir.
CREATE TABLE IF NOT EXISTS public.push_settings (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  webhook_url text NOT NULL,
  webhook_secret text NOT NULL
    DEFAULT replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
  is_enabled boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.push_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.push_settings FROM anon, authenticated;

INSERT INTO public.push_settings (id, webhook_url)
VALUES (1, 'https://www.oztdigital.com.tr/api/bildirim/gonder')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------
-- 3) Tetikleyici
-- ---------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.queue_push_notification()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event text;
  v_settings public.push_settings%ROWTYPE;
BEGIN
  IF TG_TABLE_NAME = 'orders' THEN
    IF TG_OP = 'INSERT' THEN
      v_event := 'order:new';
    ELSIF NEW.status = 'ready' AND OLD.status IS DISTINCT FROM 'ready' THEN
      v_event := 'order:ready';
    END IF;
  ELSIF TG_TABLE_NAME = 'service_requests' AND TG_OP = 'INSERT' THEN
    v_event := 'request:new';
  END IF;

  IF v_event IS NULL OR NEW.restaurant_id IS NULL THEN
    RETURN NULL;
  END IF;

  BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.push_subscriptions WHERE restaurant_id = NEW.restaurant_id) THEN
      RETURN NULL;
    END IF;

    SELECT * INTO v_settings FROM public.push_settings WHERE id = 1;
    IF NOT FOUND OR NOT v_settings.is_enabled THEN
      RETURN NULL;
    END IF;

    PERFORM net.http_post(
      url := v_settings.webhook_url,
      body := jsonb_build_object('event', v_event, 'id', NEW.id, 'restaurant_id', NEW.restaurant_id),
      headers := jsonb_build_object('Content-Type', 'application/json', 'x-ozt-secret', v_settings.webhook_secret),
      timeout_milliseconds := 10000
    );
  EXCEPTION WHEN others THEN
    NULL;
  END;

  RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.queue_push_notification() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS orders_push_notification ON public.orders;
CREATE TRIGGER orders_push_notification
AFTER INSERT OR UPDATE OF status ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.queue_push_notification();

DROP TRIGGER IF EXISTS service_requests_push_notification ON public.service_requests;
CREATE TRIGGER service_requests_push_notification
AFTER INSERT ON public.service_requests
FOR EACH ROW EXECUTE FUNCTION public.queue_push_notification();
