-- OZT DIGITAL MENU
-- Saha satış: ziyaret edilen işletmeler (adaylar), görüşme notları, fotoğraflar
--
-- Yalnızca sistem yöneticileri kullanır. Tablolar tarayıcıdan okunamaz
-- (RLS açık, politika yok); sistem paneli yetki kontrolünden sonra sunucuda
-- service role ile erişir. Fotoğraflar herkese kapalı "sales-photos"
-- deposunda tutulur ve süreli bağlantıyla gösterilir.

CREATE TABLE IF NOT EXISTS public.sales_leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 120),
  business_type text NOT NULL DEFAULT 'kafe'
    CHECK (business_type IN ('kafe', 'restoran', 'pastane', 'bar', 'otel', 'diger')),
  district text,
  address text,
  table_count integer CHECK (table_count IS NULL OR table_count BETWEEN 0 AND 1000),
  contact_name text,
  contact_role text,
  phone text,
  instagram text,
  current_menu text NOT NULL DEFAULT 'bilinmiyor'
    CHECK (current_menu IN ('basili', 'kendi_qr', 'rakip', 'yok', 'bilinmiyor')),
  competitor text,
  stage text NOT NULL DEFAULT 'yeni'
    CHECK (stage IN ('yeni', 'gorusuldu', 'ilgileniyor', 'teklif', 'demo', 'kazanildi', 'kaybedildi')),
  lost_reason text
    CHECK (lost_reason IS NULL OR lost_reason IN ('fiyat', 'rakip', 'ilgisiz', 'zaten_var', 'karar_verici_yok', 'kapandi', 'diger')),
  interest text CHECK (interest IS NULL OR interest IN ('sicak', 'ilik', 'soguk')),
  latitude double precision,
  longitude double precision,
  offer_plan text CHECK (offer_plan IS NULL OR offer_plan IN ('starter', 'pro', 'premium')),
  offer_price numeric(10, 2),
  offer_note text,
  next_action_at timestamptz,
  next_action text,
  photos text[] NOT NULL DEFAULT '{}',
  demo_restaurant_id bigint REFERENCES public.restaurants(id) ON DELETE SET NULL,
  restaurant_id bigint REFERENCES public.restaurants(id) ON DELETE SET NULL,
  note text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sales_leads_stage_idx ON public.sales_leads (stage);
CREATE INDEX IF NOT EXISTS sales_leads_next_action_idx ON public.sales_leads (next_action_at);
CREATE INDEX IF NOT EXISTS sales_leads_updated_idx ON public.sales_leads (updated_at DESC);

CREATE TABLE IF NOT EXISTS public.sales_visits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id bigint NOT NULL REFERENCES public.sales_leads(id) ON DELETE CASCADE,
  channel text NOT NULL DEFAULT 'yuz_yuze'
    CHECK (channel IN ('yuz_yuze', 'telefon', 'whatsapp', 'sistem')),
  interest text CHECK (interest IS NULL OR interest IN ('sicak', 'ilik', 'soguk')),
  note text NOT NULL DEFAULT '',
  next_step text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sales_visits_lead_idx ON public.sales_visits (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sales_visits_created_idx ON public.sales_visits (created_at DESC);

ALTER TABLE public.sales_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_visits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.sales_leads FROM anon, authenticated;
REVOKE ALL ON public.sales_visits FROM anon, authenticated;

-- Görüşme fotoğrafları: herkese kapalı depo (en fazla 5 MB, yalnızca görsel).
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('sales-photos', 'sales-photos', false, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO NOTHING;
