-- OZT DIGITAL MENU
-- İletişim formu: oztdigital.com.tr ana sayfasından gelen talepler
--
-- Form sunucu üzerinden (yetkisiz kullanım ve spam denetimiyle) yazılır;
-- tablo tarayıcıdan okunamaz ve yazılamaz (RLS açık, politika yok).
-- Talepler sistem panelinde "İletişim talepleri" sayfasında görünür.

CREATE TABLE IF NOT EXISTS public.contact_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (char_length(name) BETWEEN 2 AND 80),
  business_name text CHECK (business_name IS NULL OR char_length(business_name) <= 120),
  phone text CHECK (phone IS NULL OR char_length(phone) <= 30),
  email text CHECK (email IS NULL OR char_length(email) <= 160),
  city text CHECK (city IS NULL OR char_length(city) <= 80),
  topic text NOT NULL DEFAULT 'genel'
    CHECK (topic IN ('demo', 'paket', 'urun', 'destek', 'genel')),
  message text CHECK (message IS NULL OR char_length(message) <= 2000),
  status text NOT NULL DEFAULT 'yeni' CHECK (status IN ('yeni', 'arandi', 'kapandi')),
  admin_note text CHECK (admin_note IS NULL OR char_length(admin_note) <= 1000),
  lead_id bigint,
  source text,
  ip_hash text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contact_requests_reachable CHECK (phone IS NOT NULL OR email IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS contact_requests_created_idx ON public.contact_requests (created_at DESC);
CREATE INDEX IF NOT EXISTS contact_requests_status_idx ON public.contact_requests (status);
CREATE INDEX IF NOT EXISTS contact_requests_ip_idx ON public.contact_requests (ip_hash, created_at DESC);

ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.contact_requests FROM anon, authenticated;

-- Saha satışa aktarılan talep, o işletme kaydına bağlanır.
DO $$
BEGIN
  IF to_regclass('public.sales_leads') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint WHERE conname = 'contact_requests_lead_fk'
     ) THEN
    ALTER TABLE public.contact_requests
      ADD CONSTRAINT contact_requests_lead_fk
      FOREIGN KEY (lead_id) REFERENCES public.sales_leads(id) ON DELETE SET NULL;
  END IF;
END $$;
